export const funFactsJson = { 
    "Kobe Bryant": "Kobe Bryant is a 5x NBA champion and a 2x Finals MVP.",
    "Tim Duncan": "Tim Duncan is a 5x NBA champion and a 3x Finals MVP.",
    "Dirk Nowitzki": "Dirk Nowitzki is a 1x NBA champion and a 1x Finals MVP.", 
    "Dwyane Wade": "Dwyane Wade is a 3x NBA champion and a 1x Finals MVP.", 
    "Kevin Durant": "Kevin Durant is a 2x NBA champion and a 2x Finals MVP.",
    "Stephen Curry": "Stephen Curry is a 3x NBA champion and a 2x regular season MVP.",
    "Nikola Jokić": "Nikola Jokić is a 1x regular season MVP.",
    "Giannis Antetokounmpo": "Giannis Antetokounmpo is a 1x NBA champion and a 1x Finals MVP.",
    "Luka Dončić": "Luka Dončić won the Rookie of the Year award in 2019. Before being traded to the Mavericks, he was originally drafted to the Atlanta Hawks in Georgia, (where Rahul Chawla grew up).",
    "Damian Lillard": "Damian Lillard can shoot all the way from mid-court. He grew up in the Bay Area (like Akshay Sathiya).",
    "Chris Paul": "Chris Paul is a 4x league leader in assists per game.",
    "James Harden": "James Harden is a 3x league leader in points per game.",
    "Jayson Tatum": "Jayson Tatum is a 2x NBA All-Star.",
    "LeBron James": "LeBron James is a 4x NBA champion and 4x Finals MVP. He also won his first championship in Miami (where Sanket Manjesh grew up)",
    "Jimmy Butler": "Jimmy Butler is a 1x league leader in steals.",
    "Anthony Davis": "Anthony Davis is a 1x NBA champion.",
    "Rudy Gobert": "Rudy Gobert is a 3x Defensive Player of the Year.",
    "Bradley Beal": "Bradley Beal is a 3x NBA All-Star.",
    "Bam Adebayo": "Bam Adebayo is a 1x NBA All-Star.",
    "Devin Booker": "Devin Booker is a 2x NBA All-Star.",
    "Joel Embiid": "Joel Embiid is a 4x NBA All-Star.",
    "Paul George": "Paul George is a 7x NBA All-Star.",
    "Kyrie Irving": "Kyrie Irving is a 1x NBA champion.",
    "Kawhi Leonard": "Kawhi Leonard is a 2x NBA champion and 2x Finals MVP.",
    "Ben Simmons": "Ben Simmons won the Rookie of the Year award in 2018.",
    "Zion Williamson": "Zion Williamson is a 1x NBA All-Star.",
    "Karl-Anthony Towns": "Karl-Anthony Towns is a 2x NBA All-Star.",
    "Donovan Mitchell": "Donovan Mitchell is a 2x NBA All-Star.",
    "Jaylen Brown": "Jaylen Brown is a 1x NBA All-Star, and went to Wheeler High School (same as Pranav Khorana)."
};